/*******************************************************************************
* File Name:   xmc13_vcm_buck_single.c
*
* Description: This file provides functions for initializing the converter
*              structure, and performing the conversion. The converter runs in
*              an ISR enabled during the initialization.
*
*              This is the voltage control buck implementation which measures
*              the output voltage with an ADC channel, calculates the error to
*              the target output voltage, process it by the 3 pole 3 zero filter
*              and applies the results to the PWM generated by the CCU8.
*
* Related Document: See README.md
*
********************************************************************************
*
*******************************************************************************
* Copyright 2022-2023, Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
*
* This software, including source code, documentation and related
* materials ("Software") is owned by Cypress Semiconductor Corporation
* or one of its affiliates ("Cypress") and is protected by and subject to
* worldwide patent protection (United States and foreign),
* United States copyright laws and international treaty provisions.
* Therefore, you may use this Software only as provided in the license
* agreement accompanying the software package from which you
* obtained this Software ("EULA").
* If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
* non-transferable license to copy, modify, and compile the Software
* source code solely for use in connection with Cypress's
* integrated circuit products.  Any reproduction, modification, translation,
* compilation, or representation of this Software except as specified
* above is prohibited without the express written permission of Cypress.
*
* Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
* reserves the right to make changes to the Software without notice. Cypress
* does not assume any liability arising out of the application or use of the
* Software or any product or circuit described in the Software. Cypress does
* not authorize its products for use in any products where a malfunction or
* failure of the Cypress product may reasonably be expected to result in
* significant property damage, injury or death ("High Risk Product"). By
* including Cypress's product in a High Risk Product, the manufacturer
* of such system or application assumes all risk of such use and in doing
* so agrees to indemnify Cypress against all liability.
*******************************************************************************/
#include "cybsp.h"
#include "cy_utils.h"
#include "xmc_3p3z_filter_fixed.h"
#include "xmc13_vcm_buck_single.h"

#if (UC_FAMILY == XMC1)
/*******************************************************************************
* Macros
********************************************************************************/
/* Here 3p3z filter is used in the compensator as per the below equation.
* y[n] = B0*x[n] + B1*x[n-1] + B2*x[n-2] +
*  B3*x[n-3] + A1*y[n-1] + A2*y[n-2] + A3*y[n-3]
* Coefficients for the filter is shown below.
* These coefficients are calculated for the following configuration.
*
* Vout             = 3.3 V
* Switching freq   = 100 kHz
* Crossover freq   = 5 kHz
* Phase margin     = 50 degrees
* PWM master clock = 64 MHz
* ADC resolution   = 12 bits
* Max duty         = 90%
*/
#define B0 (+0.649757898241)
#define B1 (-0.582384858571)
#define B2 (-0.649256971688)
#define B3 (+0.582885785125)
#define A1 (+1.335491183190)
#define A2 (-0.211704021559)
#define A3 (-0.123787161631)
#define K (+0.657007535988)
#define REF (3300)
#define DUTY_TICKS_MIN (0)
#define DUTY_TICKS_MAX (576)

#if ENABLE_XMC_DEBUG_PRINT
static bool LOOP_ENTER = false;
#endif

/*******************************************************************************
* Global Variable
*******************************************************************************/
volatile XMC_VADC_RESULT_SIZE_t adc_result =0;
/* Definition of the structure to store the filter paremeters*/
XMC_3P3Z_DATA_FIXED_t ctrlFixed;

/*******************************************************************************
* Function Name: VADC0_G1_0_IRQHandler
********************************************************************************
* Summary:
* Interrupt service routine triggered by the ADC which is used for reading the
* output voltage. The compensator algorithm is running inside this ISR.
* The compensator calculates the PWM compare values for the next cycle and
* writes it to the compare register of the PWM.
*
* Parameters:
*  void
*
* Return:
*  void
*
*******************************************************************************/
void VADC0_G1_0_IRQHandler(void)
{
    /* Retrieve result from result register. */
    adc_result = XMC_VADC_GROUP_GetResult(VADC_G1, 5);

    /* Applying the filter to the ADC measured value */
    XMC_3P3Z_FilterFixed(&ctrlFixed);

    /* Updating the compare value 1 of the CCU8 */
    CCU80_CC80->CR1S= ctrlFixed.m_pOut;

    /* Enabling shadow transfer */
    ((XMC_CCU8_MODULE_t*) CCU80_BASE)->GCSS= 0x1;
}

/*******************************************************************************
* Function Name: xmc13_vcm_buck_single_init
********************************************************************************
* Summary:
* Function performing the initialization of the compensator, peripherals used,
* and interrupt.
*
* Parameters:
*  void
*
* Return:
*  void
*
*******************************************************************************/
void xmc13_vcm_buck_single_init(void)
{
    /* Initializing the interrupt. */
    NVIC_SetPriority(VADC0_G1_0_IRQn,
    NVIC_EncodePriority(NVIC_GetPriorityGrouping(),
                        63,
                        0));

    /* Enable the interrupt. */
    NVIC_EnableIRQ(VADC0_G1_0_IRQn);

    /* Initializing the compensator with the values for the required regulator
    configuration. */
    XMC_3P3Z_InitFixed(&ctrlFixed,
                       B0,
                       B1,
                       B2,
                       B3,
                       A1,
                       A2,
                       A3,
                       K,
                       REF,
                       DUTY_TICKS_MIN,
                       DUTY_TICKS_MAX,
                       (uint32_t*)&adc_result);

    /* Enable CCU80 Clock. */
    XMC_CCU8_EnableClock(CCU80_BASE, CCU80_CC80);

    /* Start CCU80 timer. */
    XMC_CCU8_SLICE_StartTimer((XMC_CCU8_SLICE_t*) CCU80_CC80);
}

#endif /*(UC_FAMILY == XMC1)*/
/* [] END OF FILE */
